spring:
  # Development Database Configuration
#  datasource:
#    url: jdbc:mysql://localhost:3306/shoesstore_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 2211
#
#  # JPA Configuration for Development
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/shoesstore_db
    username: postgres
    password: 123456
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Development Logging - Only DB, errors, and app logs
logging:
  level:
    com:
      ds: INFO
    org:
      springframework:
        security: WARN
        # SQL: DEBUG
        # type.descriptor.sql.BasicBinder: TRACE
        web: WARN
        boot: WARN
        data: WARN
        transaction: WARN
        orm: WARN
      hibernate:
        SQL: WARN
        engine:
          jdbc:
            spi:
              SqlExceptionHelper: WARN
    root: WARN
  # Disable Hibernate query logging
  org.hibernate.SQL: WARN
  org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Development Configuration
app:
  admin:
    email: admin@mail.mail
    username: admin
    password: admin
  startup:
    create-dev-datas: true
momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz

  # Endpoint
  create-endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  query-endpoint: https://test-payment.momo.vn/v2/gateway/api/query

  # Callback URLs
  return-url: https://a1056bc73497.ngrok-free.app/api/payments/momo/return
  ipn-url: https://a1056bc73497.ngrok-free.app/api/payments/momo/ipn

  # Request Type
  request-type: payWithMethod
## ðŸš€ Google Drive Configuration
#gdrive:
#  customer-id: 717175626277-eir81eb76aa3c0bgaut9oe9ut7selmn5.apps.googleusercontent.com
#  customer-secret: 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
#  redirect-uri: http://localhost:8080/drive/oauth2/callback
python:
  api:
    url: http://127.0.0.1:8000/search
